# Generated by Django 5.0.6 on 2024-08-03 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(default="")),
                ("eliminada", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tarea",
            },
        ),
        migrations.CreateModel(
            name="Subtarea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(default="")),
                ("eliminada", models.BooleanField(default=False)),
                (
                    "id_tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desafioadl.tarea",
                    ),
                ),
            ],
            options={
                "db_table": "subtarea",
            },
        ),
    ]
